# Generated by Django 3.1.4 on 2020-12-11 03:23

from django.db import migrations, models
import django.db.models.deletion
import uuid
from doctors.data import create

def forwards_func(apps, schema_editor):
    create()

def reverse_func(apps, schema_editor):
    return


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('query_name', models.SlugField()),
                ('display_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('district', models.SlugField(max_length=100)),
                ('phone_number', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('item', models.TextField()),
                ('price', models.PositiveIntegerField(db_index=True)),
                ('remarks', models.TextField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='doctors.category')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('details', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_hours', to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('query_name', models.SlugField()),
                ('display_name', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='languages', to='doctors.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='doctors.doctor'),
        ),
        migrations.RunPython(forwards_func, reverse_func)
    ]
